# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'BBMVVMProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BBMVVMProject
  
  pod 'ReactiveCocoa', '5.0.0'
  pod 'SnapKit', '3.1.2'
  pod 'Moya', '8.0.1'
  pod 'Moya/ReactiveSwift'
  pod 'SwiftyJSON', '3.1.4'
  pod 'ObjectMapper', '2.2.2'
  pod 'Kingfisher', '3.3.2'

end
